/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Dominio.Gestor;
import Dominio.Pedido;
import UI.Controladores.GestorView;
import UI.Controladores.ProcesarPedidosGestorControlador;
import UI.Renderizadores.RenderizadorListas;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


public class GestorUI extends javax.swing.JFrame implements GestorView {
    private Gestor gestor; 
    
    // Controladores
    
    private ProcesarPedidosGestorControlador controlador;
    
    public GestorUI(Gestor gestor){
        
        initComponents();      
        
        this.gestor = gestor;
        this.controlador = new ProcesarPedidosGestorControlador(gestor, this);
                
    }
    
    @Override
    public void cargarNombreUP(String nombreGestor, String nombreUP){
        String labelContent = nombreGestor + " | Area: " + nombreUP;
        jLabel2.setText(labelContent);       
    }          
     
    @Override
    public void cargarPedidosPendientesUP(List<Pedido> pedidosPendientes) {
        try {
            DefaultListModel<Pedido> modelo = new DefaultListModel<>();

            for(Pedido p : pedidosPendientes){
                modelo.addElement(p);
            }
            
            jListadoPedidos.setModel(modelo);        
            jListadoPedidos.setCellRenderer(new RenderizadorListas<>(
                    p ->p.getItem().getNombre() + " - Cliente: " + p.getServicio().getNombreCliente() + " - " + p.getFechaHora()
            ));
        } catch (Exception ex) {
            msgError.setText(ex.getMessage());
        }
    }
    
    @Override
    public void cargarPedidosTomados(List<Pedido> pedidosTomadosPorGestor){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nombre item", "Descripcion", "Cliente", "FechaHora", "Estado"});

         for (Pedido pedido : pedidosTomadosPorGestor) {
             modelo.addRow(new Object[]{
                 pedido.getItem().getNombre(),
                 pedido.getComentario(),
                 pedido.getServicio().getNombreCliente(),
                 pedido.getFechaHora(),
                 pedido.getEstado().toString()
             });
         }

         tablaPedidosTomados.setModel(modelo);
         tablaPedidosTomados.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
         tablaPedidosTomados.revalidate();
         tablaPedidosTomados.repaint();
    }
   
    @Override
    public void tomarPedido(){
        if(this.jListadoPedidos.getSelectedValue() != null)
            this.controlador.tomarPedido(jListadoPedidos.getSelectedValue());
                
    }
    
    @Override
    public void entregarPedido(){
        int posPedido = tablaPedidosTomados.getSelectedRow();
        this.controlador.entregarPedido(posPedido);
                        
    }
    
    @Override
    public void finalizarPedido(){
        int posPedido = tablaPedidosTomados.getSelectedRow();
        this.controlador.finalizarPedidio(posPedido);
    }
    
    public void mostrarMensajeSistema(String mensaje){
        msgError.setText(mensaje);
        msgError.setVisible(true);

        Timer timer = new Timer(4000, e -> msgError.setText(""));
        timer.setRepeats(false);
        timer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListadoPedidos = new javax.swing.JList<>();
        btnTomarPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidosTomados = new javax.swing.JTable();
        btnFinalizarPedido = new javax.swing.JButton();
        btnEntregarPedido = new javax.swing.JButton();
        msgError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Unidad Procesadora");

        jLabel1.setText("Gestor y unidad Procesadora");

        jScrollPane1.setViewportView(jListadoPedidos);

        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        tablaPedidosTomados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre de item", "Descripcion", "Cliente", "FechaHora", "Estado"
            }
        ));
        tablaPedidosTomados.setToolTipText("");
        jScrollPane2.setViewportView(tablaPedidosTomados);

        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnEntregarPedido.setText("Entregar Pedido");
        btnEntregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarPedidoActionPerformed(evt);
            }
        });

        msgError.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        msgError.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setText("Mensajes del sistema: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnFinalizarPedido)
                            .addGap(18, 18, 18)
                            .addComponent(btnEntregarPedido)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgError, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnTomarPedido)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarPedido)
                    .addComponent(btnEntregarPedido))
                .addGap(18, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(msgError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
       tomarPedido();
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        finalizarPedido();
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnEntregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarPedidoActionPerformed
        entregarPedido();
    }//GEN-LAST:event_btnEntregarPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregarPedido;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<Pedido> jListadoPedidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgError;
    private javax.swing.JTable tablaPedidosTomados;
    // End of variables declaration//GEN-END:variables

    
}
