/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Dominio.Gestor;
import Dominio.Item;
import Dominio.Pedido;
import Dominio.PedidoVO;
import Dominio.Servicio;
import Dominio.Usuario;
import Servicios.Fachada;
import UI.Renderizadores.RenderizadorListas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class GestorUI extends javax.swing.JFrame {
    private Gestor gestor; 
    private Fachada f;
    
    public GestorUI(Gestor gestor) {
        
        this.gestor = gestor;
        this.f = Fachada.getInstancia();
        
        initComponents();
        
        
        cargarNombreUP(gestor);
        cargarPedidosPendientesUP();
        
        
    }
    
    
    public void cargarNombreUP(Gestor g){
        
        String labelContent = g.getNombreCompleto() + " | Area: "+ g.getNombreUP();
        jLabel2.setText(labelContent);       
    }          
    
        
    public void cargarPedidosTomadosPorGestor(Gestor g){
        
        List<Pedido> pedidosTomados = g.getPedidosTomados();
        
                
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.setColumnIdentifiers(new String[]{"Nombre de item", "Descripcion", "Cliente", "Fecha Hora", "Estado"});

        for (Pedido pedido : pedidosTomados) {
            modelo.addRow(new Object[]{
                pedido.getItem().getNombre(),
                pedido.getComentario(),
                // Cliente
                // Estado
            });
        }

        tablaPedidosTomados.setModel(modelo);

        tablaPedidosTomados.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        tablaPedidosTomados.revalidate();
        tablaPedidosTomados.repaint();
    
        
    }
    
    public void tomarPedido(Pedido p){
        
        f.tomarPedido(this.gestor,p);
    }
    
    
    public void finalizarPedido(Pedido p){
       // f.finalizarPedido(this.gestor, p);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListadoPedidos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidosTomados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        msgError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad Procesadora");

        jLabel1.setText("Gestor y unidad Procesadora");

        jScrollPane1.setViewportView(jListadoPedidos);

        jButton1.setText("TomarPedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaPedidosTomados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tablaPedidosTomados.setToolTipText("");
        jScrollPane2.setViewportView(tablaPedidosTomados);

        jButton2.setText("Finalizar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Entregar Pedido");

        msgError.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        msgError.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setText("Mensajes del sistema: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(26, 26, 26)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgError, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(msgError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   private void cargarPedidosPendientesUP() {
        try {
            // Obtener items de la fachada 
            DefaultListModel<PedidoVO> modelo = new DefaultListModel<>();
            
            for(PedidoVO p : f.getPedidosConfirmados(gestor.getUP().getNombre())){
               
                modelo.addElement(p);
                
            }

            //Configurar modelo y renderizador 
            jListadoPedidos.setModel(modelo);        
        
            jListadoPedidos.setCellRenderer(new RenderizadorListas<>(
                    p -> p.nombreCliente() + p.nombreItem() + p.fechaHora()
            ));
        } catch (Exception ex) {
            msgError.setText(ex.getMessage());

        }
   }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<PedidoVO> jListadoPedidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgError;
    private javax.swing.JTable tablaPedidosTomados;
    // End of variables declaration//GEN-END:variables
}
